DROP DATABASE NEWS;
CREATE DATABASE NEWS;
USE NEWS;

CREATE TABLE ROLE(
                     ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                     NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
                     CODE VARCHAR(255) NOT NULL,
                     CREATEDDATE TIMESTAMP NULL,
                     MODIFIEDDATE TIMESTAMP NULL,
                     CREATEDBY VARCHAR(255) NULL,
                     MODIFIEDBY VARCHAR(255) NULL
);

CREATE TABLE USER (
                      ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                      USERNAME VARCHAR(150) NOT NULL,
                      PASSWORD VARCHAR(150) NOT NULL,
                      FULLNAME VARCHAR(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
                      STATUS INT NOT NULL,
                      ROLEID BIGINT NOT NULL,
                      CREATEDDATE TIMESTAMP NULL,
                      MODIFIEDDATE TIMESTAMP NULL,
                      CREATEDBY VARCHAR(255) NULL,
                      MODIFIEDBY VARCHAR(255) NULL
);


ALTER TABLE USER ADD CONSTRAINT FK_USER_ROLE
    FOREIGN KEY (ROLEID) REFERENCES ROLE(ID);

CREATE TABLE NEWS (
                      ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                      TITLE VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
                      THUMBNAIL VARCHAR(255) NULL,
                      SHORTDESCRIPTION TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
                      CONTENT TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL ,
                      CATEGORYID BIGINT NOT NULL,
                      CREATEDDATE TIMESTAMP NULL,
                      MODIFIEDDATE TIMESTAMP NULL,
                      CREATEDBY VARCHAR(255) NULL,
                      MODIFIEDBY VARCHAR(255) NULL
);


CREATE TABLE CATEGORY (
                          ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                          NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
                          CODE VARCHAR(255) NOT NULL,
                          CREATEDDATE TIMESTAMP NULL,
                          MODIFIEDDATE TIMESTAMP NULL,
                          CREATEDBY VARCHAR(255) NULL,
                          MODIFIEDBY VARCHAR(255) NULL
);


ALTER TABLE NEWS ADD CONSTRAINT FK_NEWS_CATEGORY
    FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID);


CREATE TABLE COMMENT (
                         ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                         CONTENT TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
                         USERID BIGINT NOT NULL,
                         NEWSID BIGINT NOT NULL,
                         CREATEDDATE TIMESTAMP NULL,
                         MODIFIEDDATE TIMESTAMP NULL,
                         CREATEDBY VARCHAR(255) NULL,
                         MODIFIEDBY VARCHAR(255) NULL
);


ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_USER
    FOREIGN KEY (USERID) REFERENCES USER(ID);


ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_NEWS
    FOREIGN KEY (NEWSID) REFERENCES NEWS(ID);


INSERT INTO ROLE(CODE, NAME)
VALUES('admin','admin');
INSERT INTO ROLE(CODE, NAME)
VALUES('user','user');

INSERT INTO USER(USERNAME, PASSWORD, FULLNAME, STATUS, ROLEID)
VALUES('admin','123456','admin',1,1);
INSERT INTO USER(USERNAME, PASSWORD, FULLNAME, STATUS, ROLEID)
VALUES('nttuan','123456','Nguyen Tho Tuan',1,2);
INSERT INTO USER(USERNAME, PASSWORD, FULLNAME, STATUS, ROLEID)
VALUES('cxtuan','123456','Chau Xuan Tuan',1,2);

INSERT INTO CATEGORY(CODE, NAME)
VALUES('the-thao', 'Thể thao');
INSERT INTO CATEGORY(CODE, NAME)
VALUES('the-gioi', 'Thế giới');
INSERT INTO CATEGORY(CODE, NAME)
VALUES('thoi-su', 'Thời sự');
INSERT INTO CATEGORY(CODE, NAME)
VALUES('chinh-tri', 'Chính trị');
